[tweak] changed the kernel to the LeapPad Madrid one + compatibility

diff --git a/LF1000/packages/init/etc/init.d/cartridge b/LF1000/packages/init/etc/init.d/cartridge
--- a/LF1000/packages/init/etc/init.d/cartridge
+++ b/LF1000/packages/init/etc/init.d/cartridge
@@ -1,10 +1,20 @@
 #!/bin/sh
 
 # This script mounts misc volumes late (after AppManager starts)
+# 4/1/11 SZ Added optional 2nd param to enable read-write mode when mounting cartridge
+# USAGE:   mount start|stop|fstop|restart [-w|rw|ro=default]
 
-CART=/LF/Cart
+set -x
+CART="/LF/Cart"
 sys_ret=0
 ubi_ret=0
+
+RW="ro"
+if [ ! -z "$2" ] ; then 
+	if [ "$2" == "-w" -o "$2" == "rw" ] ; then
+		RW="rw"
+	fi
+fi
 
 case "$1" in
         start)
@@ -24,12 +34,20 @@ case "$1" in
 			fi
 
 			if [ $ubi_ret = 0 ]; then
-				mount -t vfat -o ro /dev/mtdblock$mn $where
+				mount -t vfat -o $RW /dev/mtdblock$mn $where
 				if [ $? = 0 ]; then
 					echo "Success"
 				else
-					sys_ret=21
-					logger -s -t "Emerald Base" -p local4.err "Failed mount of mtd$un to $where"
+					echo "************************************"
+					echo "Retrying the mount once"
+					echo "************************************"
+					mount -t vfat -o $RW /dev/mtdblock$mn $where
+					if [ $? = 0 ]; then
+						echo "Success"
+					else
+						sys_ret=21
+						logger -s -t "Emerald Base" -p local4.err "Failed mount of mtd$un to $where"
+					fi
 				fi
 			else
 				sys_ret=11
@@ -102,7 +120,7 @@ case "$1" in
 		$0 start
 		;;
 	*)
-		echo "Usage: $0 {start|stop|restart}"
+		echo "Usage: $0 {start|stop|fstop|restart} [-w|rw|ro=default]"
 		exit 1
 		;;
 esac
diff --git a/LF1000/packages/init/etc/init.d/rcS b/LF1000/packages/init/etc/init.d/rcS
--- a/LF1000/packages/init/etc/init.d/rcS
+++ b/LF1000/packages/init/etc/init.d/rcS
@@ -10,19 +10,44 @@ mount -t tmpfs mdev /dev
 /usr/bin/make_dev_nodes.sh
 mount -a; $TIM done "mount -a"
 
-# FIXME: Have to put keyboard input device in before mdev -s or vbus
-# input events don't work (e.g. /usr/bin/surgeon-usb-socket, vbus-monitor).
-# Remove this once this driver is generating hotplug events instead.
-modprobe lf1000_udc
+if grep /dev/root.*ext4 /proc/mounts > /dev/null; then
+	mount -o,remount,noatime,noauto_da_alloc,barrier=0 /
+fi
 
-# initial mdev device enumeration
-mdev -s; $TIM end mdev -s
+#Mount bulk early because it's fast on SD
+#NOTE: This could be even faster if moved to fstab, but it could break ATAP
+if [ `cat /sys/devices/platform/lf1000-gpio/boot_image` = "PLAY" ]; then
+	$TIM begin "mounts";
+	/etc/init.d/mounts start;
+	$TIM done "mounts"
+fi
+
+# FIXME: Show version -- This doesn't even work!
+# if grep B /sys/devices/platform/lf1000-gpio/board_id > /dev/null; then
+#  	/usr/bin/drawtext-fb /dev/fb0 /var/fonts/monotext8x16.rgb "LPAD rcS `cat /etc/version`" 10 5 1
+# fi
+
+# load audio drivers
+/etc/init.d/alsa start
 
 # set host name using serial number
 hostname Explorer-`mfgdata get sn`
 
+# configure POP audio if selected
+if [ -e /flags/pop ]; then
+	if [ -e /sys/devices/platform/didj-asoc/force_audio ]; then
+		echo 1 > /sys/devices/platform/didj-asoc/force_audio
+	fi
+	if [ -e /sys/devices/platform/didj-asoc/force_mixer ]; then
+		echo 1 > /sys/devices/platform/didj-asoc/force_mixer
+	fi
+fi
+
 # Speed NAND up
 /usr/bin/faster-nand-timing
+
+# start low-level settings daemon
+/etc/init.d/lfd start
 
 # Stop showing movie
 # touch /tmp/splash
@@ -31,7 +56,7 @@ hostname Explorer-`mfgdata get sn`
 ATAP=0
 if [ `grep lf1000-nor /proc/iomem | cut -d '-' -f 1` = "84000000" ]; then
 	if [ `cat /sys/devices/platform/lf1000-gpio/board_id` != 3 ]; then
-		ATAP=1
+		ATAP=0 # Don't enable for now...  
 	fi
 fi
 
@@ -67,19 +92,33 @@ else
 	# Log Keep-alives
 	/usr/bin/show-scr | head -1 | logger -s -t "Recovery Keep-Alives" -p local4.notice
 
-	# 8 second delay for first boot... about 6 seconds from here
-	if [ `cat /sys/devices/platform/lf1000-gpio/power` = "COLD" ]; then
-		# But real developers will not want this at all!!
-		if [ ! -e /flags/no8sec ]; then
-			echo "Twiddle thumbs for 6 seconds more..."
-			sleep 6;
-		fi
-	fi
+	# # 8 second delay for first boot... about 6 seconds from here
+	# if [ `cat /sys/devices/platform/lf1000-gpio/power` = "COLD" ]; then
+	# 	# But real developers will not want this at all!!
+	# 	if [ ! -e /flags/no8sec ]; then
+	# 		echo "Twiddle thumbs for 6 seconds more..."
+	# 		sleep 6;
+	# 	fi
+	# fi
 
 	# Sound and other misc, in background, but early
 	(
 		# Display screen before sound starts
-		imager /dev/layer0 /var/screens/LEGAL.png
+
+		LANGUAGE=`mfgdata get locale | cut -d '-' -f1`
+		SCREEN=/var/screens-$LANGUAGE/LEGAL.png
+		if [ ! -r "$SCREEN" ]; then
+			# If we can't find it, the default to english
+			logger -s -t "Emerald Base" -p local4.notice "Locale: could not find $SCREEN, defaulting to english"
+			SCREEN=/var/screens/LEGAL.png
+		fi
+		if grep B /sys/devices/platform/lf1000-gpio/board_id > /dev/null; then
+			SCREEN=/var/screens/Madrid-Boot-logoCW.png
+		fi
+		logger -s -t "Emerald Base" -p local4.notice "Locale: Loading $SCREEN"
+		imager-fb /dev/fb0 "$SCREEN"
+
+		
 		# Ensure that the bus clock is set up for 144MHz to give the
 		# correct USB host clock rate.  Older bootstraps set the clock
 		# to 147MHz so we'll change it here and hide the "flicker" in
@@ -94,16 +133,21 @@ else
 
 		# restore volume setting if one exists
 		if [ -e /flags/volume ]; then
-			cat /flags/volume > /sys/devices/platform/lf1000-audio/volume
+			lfd-ctrl set volume `cat /flags/volume`
+		else
+			lfd-ctrl set volume 6
 		fi
 
 		# play sound
 		( $TIM begin "sounds/startup.wav"
-		  oss -w /var/sounds/startup.wav; $TIM end "sounds/startup.wav"
+		  aplay /var/sounds/startup.wav; $TIM end "sounds/startup.wav"
 		) &
 
-		# Set Backlight low-setting.  This is the physical value to use for lowest backlight brightness
-		mfgdata get bl > /sys/devices/platform/lf1000-dpc/backlight_threshold
+		# Set Backlight low-setting.  This is the physical value to use
+		# for lowest backlight brightness
+		if [ -e /sys/devices/platform/lf1000-dpc/backlight_threshold ]; then
+			mfgdata get bl > /sys/devices/platform/lf1000-dpc/backlight_threshold
+		fi
 
 		# if nonzero NOR values then set battery ADC slope and offset 
 		if [ "`mfgdata get adc`" != "0 0" ]; then
@@ -121,6 +165,14 @@ else
 		/etc/init.d/touchscreen start; # $TIM done "touchscreen" 
 		/usr/bin/setcal; # $TIM done "setcal"
 
+		# TTpro 978 Restore time from file system if cold booting, and flush to RTC
+		# TTpro 1297, test for /flags/lasttime be present too
+		if [ `cat /sys/devices/platform/lf1000-gpio/power` = "COLD" -a -e /flags/lasttime ]; then
+			logger -s -t "Emerald Base" -p local4.notice "Cold Boot; Setting clock to /flags/lasttime=$(cat /flags/lasttime)"
+			date -D %s $(cat /flags/lasttime)
+			hwclock --systohc
+		fi
+
 		# set date to avoid errors in mq_timesend() and mq_timereceive() POSIX funcs
 		if [[ `date +%Y` -lt "2008" -o "2030" -lt `date +%Y` ]]
 		then
@@ -130,14 +182,16 @@ else
 
 	) &
 
+	# This is a calculated race with AppManager, who needs this
+	# working within a couple seconds of his starting up.
+	# ( sleep 2; 
+	#	$TIM begin "mounts at 2s";
+	#	/etc/init.d/mounts start;
+	#	$TIM done "mounts"
+	# ) &
 
-	# This is a calculated race with AppManager, who needs this working
-	# within a couple seconds of his starting up.
-	( sleep 2; 
-		$TIM begin "mounts at 2s";
-		/etc/init.d/mounts start;
-		$TIM done "mounts"
-			) &
+	#Start sync demon
+	nice -10 /usr/bin/syncd &
 
 	# Late start these guys in background
 	( sleep 10; $TIM begin "Rest of networking at 10s";
@@ -156,11 +210,14 @@ else
 
 	( sleep 15; $TIM begin "Version Logging at 15s"
 		BOOT_DEV=/dev/`grep NOR_Boot /proc/mtd | cut -d : -f 1`
+		nice -10 get-bootstrap-version < $BOOT_DEV > /tmp/eb
 		logger -s -t "Emerald Base" -p local4.notice "hostname:         '`hostname`'"
 		logger -s -t "Emerald Base" -p local4.notice "Board ID:         '`cat /sys/devices/platform/lf1000-gpio/board_id`'"
-		logger -s -t "Emerald Base" -p local4.notice "NOR BootVersion:  '`nice -10 get-bootstrap-version < $BOOT_DEV`'"  # 0.3s
+		logger -s -t "Emerald Base" -p local4.notice "NOR BootVersion:  '`cat /tmp/eb`'"  # 0.3s
 		logger -s -t "Emerald Base" -p local4.notice "NOR SerialNumber: '`mfgdata get sn`'"
-		logger -s -t "Emerald Base" -p local4.notice "NAND BootVersion: '`nice -10 get-bootstrap-version < /dev/mtd0`'" # 0.6s
+		if ! grep B /sys/devices/platform/lf1000-gpio/board_id > /dev/null; then
+			logger -s -t "Emerald Base" -p local4.notice "NAND BootVersion: '`nice -10 get-bootstrap-version < /dev/mtd0`'" # 0.6s
+		fi
 		/etc/init.d/logversion;
 		$TIM end "Version Logging"
 	) &
@@ -185,8 +242,5 @@ else
 		$TIM begin "app"
 		echo "Launching AppManager normally"
 		/usr/bin/app &	
-		# Set background color from white to black
-		mlc-control /dev/mlc set background 000000
-		mlc-control /dev/mlc set dirty
 	fi
 fi
diff --git a/LF1000/packages/init/etc/init.d/recovery-mounts b/LF1000/packages/init/etc/init.d/recovery-mounts
--- a/LF1000/packages/init/etc/init.d/recovery-mounts
+++ b/LF1000/packages/init/etc/init.d/recovery-mounts
@@ -9,11 +9,17 @@ if [ ! -e $SYS ]; then
 	exit 1
 fi
 
+# Madrid/ext?
+EXT=0
+if [ -e /sys/block/mmcblk0 ]; then
+	EXT=1
+fi
+
 # Two mounts points and flags to indicate doneness
 mp_root=/patient-rfs
 mp_bulk=/patient-bulk
 tp0=/tmp/ready_
-fs=/var/1.1.0.fs
+fs=/var/1.2.0.fs
 
 operation="$1"
 shift
@@ -49,7 +55,32 @@ case "$operation" in
 		if [ $operation == startro ]; then
 			rwmode=ro
 		fi
-		# Process each mount point we're interested
+
+		# For Madrid, do mounts the "easy" way.  [Not so easy now!]
+		if [ $EXT = 1 ]; then
+			# Process each mount point we're interested in
+			while read dev where name; do
+				# Early out if already mounted
+				if grep $dev /proc/mounts > /dev/null; then
+					echo "$dev already mounted"
+					continue;
+				fi
+				mount -o $rwmode $dev $where
+				if [ $? != 0 ]; then
+					echo "failed to mount $dev $where."
+				else
+					echo "success mounting $uv"
+				fi
+				# We're done: leave a flag 
+				touch ${tp0}$name
+			done <<EOF
+/dev/mmcblk0p3 $mp_root rfs
+/dev/mmcblk0p4 $mp_bulk bulk
+EOF
+			exit 0; # Early out for Madrid
+		fi
+
+		# Process each mount point we're interested in
 		# Get data from "here doc" about 50 lines down from, uh, here.
 		while read match name uv where; do
 			# Find match in $fs
@@ -95,7 +126,7 @@ case "$operation" in
 				fi
 				get_ud "$uv"
 				if [ -z "$ud" ]; then
-					echo "Failed to find $UV in /sys!  Impossible!!!"
+					echo "Failed to find $uv in /sys!  Impossible!!!"
 					continue;
 				fi
 			else
@@ -129,6 +160,25 @@ bulk.ubi Bulk ubi_bulk $mp_bulk
 EOF
 		;;
 	stop)
+		# For Madrid, do mounts the "easy" way.  [Not so easy now!]
+		if [ $EXT = 1 ]; then
+			for uv in /dev/mmcblk0p3 /dev/mmcblk0p4; do
+				# umount
+				if grep $uv /proc/mounts > /dev/null; then
+					umount $uv
+					res=$?
+					if [ $res != 0 ]; then
+						echo "failed to umount $uv $where: exit=$res"
+					else
+						echo "success: umount $where"
+					fi
+				else
+					echo "No mount for $uv found"
+				fi
+			done
+			exit 0; # Early out for Madrid
+		fi
+
 		# Undo three steps in reverse order
 		# 3) umount
 		# 2) ubi detach
@@ -137,7 +187,7 @@ EOF
 		while read uv; do
 			# umount
 			if grep $uv /proc/mounts > /dev/null; then
-				where=`awk /$uv/' { print $2; }' proc/mounts`
+				where=`awk /$uv/' { print $2; }' /proc/mounts`
 				umount $where
 				res=$?
 				if [ $res != 0 ]; then
diff --git a/LF1000/packages/init/usr/bin/setcal b/LF1000/packages/init/usr/bin/setcal
--- a/LF1000/packages/init/usr/bin/setcal
+++ b/LF1000/packages/init/usr/bin/setcal
@@ -1,17 +1,72 @@
 #!/bin/sh
 
-# Load the touchscreen calibration into the touchscreen driver
+log ()
+{
+	echo $1
+	logger -s -t "Emerald Base" -p local4.notice "$1"
+}
+
+# See if we find a new calibration file for non-pointercal data
+NEWCAL=/flags/set-ts.sh
+if [ -x $NEWCAL -a -s $NEWCAL ]; then
+	log "setcal: Reading TS sensitivity calibration data from $NEWCAL"
+else
+	log "setcal: Missing TS sensitivity calibration data file: $NEWCAL"
+	log "setcal: Creating new one from 'tsp' region in NOR..."
+	mfgdata get tsp > $NEWCAL
+	chmod +x $NEWCAL
+fi
+
+# Run it
+$NEWCAL
+if [ $? == 0 ]; then
+	log "setcal: $NEWCAL success"
+	# Based on version, set "tails" flag on for older, off for newer
+	SYS=/sys/devices/platform/lf1000-touchscreen
+	version=$(grep "Version=" $NEWCAL | cut -d = -f 2)
+	tails=0 # Fix bug for newer calibrations
+	if [ $version -lt 4 ]; then
+		tails=1 # Older calibrations, leave bug on
+	fi
+	log "setcal: Setting tails to $tails based on $NEWCAL version $version"
+	echo $tails > $SYS/tails
+else
+	if grep "ILI6480G2" /proc/cmdline > /dev/null; then
+		log "setcal: $NEWCAL generated from missing or corrupted NOR 'tsp' data; using defaults for 5inch"
+		SYS=/sys/devices/platform/lf1000-touchscreen
+		echo 50 > $SYS/max_tnt_down
+		echo 500 > $SYS/min_tnt_up
+		echo 20 > $SYS/max_delta_tnt
+		echo 30 > $SYS/delay_in_us
+		echo 15 > $SYS/y_delay_in_us
+		echo 40 > $SYS/tnt_delay_in_us
+		echo "384 777 806 821 848 1061 1102 1133 1186" > $SYS/pressure_curve
+		# ILI9322
+		# NT39016
+		# HX8238
+	else
+		log "setcal: $NEWCAL generated from missing or corrupted NOR 'tsp' data; using defaults for 3inch"
+	fi
+	# log "setcal: ###### To remove this message, please calibrate with ######"
+	# log "setcal: ###### new-calib, then run this line to update NOR:  ######"
+	# log "setcal: ###### mfgdata set tspr `cat /tmp/mfgdata-tspr-data` ######"
+fi
+
+# Load the touchscreen calibration matrix into the touchscreen driver
 USERCAL=/flags/pointercal
 MFGDATA=/usr/bin/mfgdata
 DEFAULT=/sys/devices/platform/lf1000-touchscreen/pointercal
 SETCAL=/sys/devices/platform/lf1000-touchscreen
 
-# Add ability to force calibration by holding hint during boot
-. /usr/bin/recovery-functions
-if button_down $BUTTON_HINT; then
-	touch /tmp/force_cal # force calibration
-	touch /tmp/splash # skip movie too
-fi
+# RTD 7/18/2011: Remove this because Madrids were getting mysteriously recal'd
+# and we think this is because it was too easy to enter cal program
+# 
+## Add ability to force calibration by holding hint during boot
+# . /usr/bin/recovery-functions
+# if button_down $BUTTON_HINT || button_down $BUTTON_ESC; then
+# 	touch /tmp/force_cal # force calibration
+# 	touch /tmp/splash # skip movie too
+# fi
 
 validate ()
 {
@@ -42,13 +97,14 @@ validate ()
 # Give to driver
 accept ()
 {
-	echo $3 > $SETCAL/a0
-	echo $1 > $SETCAL/a1
-	echo $2 > $SETCAL/a2
-	echo $6 > $SETCAL/a3
-	echo $4 > $SETCAL/a4
-	echo $5 > $SETCAL/a5
-	echo $7 > $SETCAL/a6
+	# echo $3 > $SETCAL/a0
+	# echo $1 > $SETCAL/a1
+	# echo $2 > $SETCAL/a2
+	# echo $6 > $SETCAL/a3
+	# echo $4 > $SETCAL/a4
+	# echo $5 > $SETCAL/a5
+	# echo $7 > $SETCAL/a6
+	echo $* > $DEFAULT
 }
 
 # Atomic Save in NAND for faster access next time
@@ -60,12 +116,6 @@ save ()
 	# is an atomic write (i.e, mv).  And /flags is 777, so anyone can mv.
 	sync # I want fsync here, but I don't know how to get it.
 	mv $USERCAL.new $USERCAL
-}
-
-log ()
-{
-	echo $1
-	logger -s -t "Emerald Base" -p local4.notice "$1"
 }
 
 # Pick the best pointercal data we can find...
diff --git a/LF1000/packages/init/usr/bin/trapdoor b/LF1000/packages/init/usr/bin/trapdoor
--- a/LF1000/packages/init/usr/bin/trapdoor
+++ b/LF1000/packages/init/usr/bin/trapdoor
@@ -1,10 +1,19 @@
 #!/bin/sh
 
-imager /dev/layer0 /var/screens/UPDATE_IN_PROGRESS.png
-drawtext /dev/layer0 /var/fonts/monotext8x16.rgb " Test Mode " 12 12 1
+if [ -e /sys/class/graphics ]; then
+	imager-fb /dev/fb0 /var/screens/UPDATE_IN_PROGRESS.png
+	drawtext-fb /dev/fb0 /var/fonts/monotext8x16.rgb " Test Mode " 12 12 1
+	MLC="0"
+else
+	imager /dev/layer0 /var/screens/UPDATE_IN_PROGRESS.png
+	drawtext /dev/layer0 /var/fonts/monotext8x16.rgb " Test Mode " 12 12 1
+	MLC="1"
+fi
 
 # Set Backlight low-setting.  This is the physical value to use for lowest backlight brightness
-mfgdata get bl > /sys/devices/platform/lf1000-dpc/backlight_threshold
+if [ -e /sys/devices/platform/lf1000-dpc/backlight_threshold ]; then
+	mfgdata get bl > /sys/devices/platform/lf1000-dpc/backlight_threshold
+fi
 
 # if nonzero NOR values then set battery ADC slope and offset 
 if [ "`mfgdata get adc`" != "0 0" ]; then 
@@ -70,7 +79,15 @@ if [ -e /LF/Base/EmeraldMfgTest/LaunchMfgTest.sh ] ; then
 	logger -s -t "Emearld App" -p local4.notice "Launched Mfg Test from trapdoor mode"
 	echo "Trap door mode....starting Mfg Test!!"
 	chmod -R +x /LF/Base/EmeraldMfgTest
-	./LF/Base/EmeraldMfgTest/LaunchMfgTest.sh &
+	/LF/Base/EmeraldMfgTest/LaunchMfgTest.sh &
+	/etc/init.d/telnetd start
+	/etc/init.d/vsftpd start
+	exit 0
+elif [ -e /LF/Base/MadridMfgTest/LaunchMfgTest.sh ] ; then 
+	logger -s -t "Madrid App" -p local4.notice "Launched Mfg Test from trapdoor mode"
+	echo "Trap door mode....starting Mfg Test!!"
+	chmod -R +x /LF/Base/MadridMfgTest
+	/LF/Base/MadridMfgTest/LaunchMfgTest.sh &
 	/etc/init.d/telnetd start
 	/etc/init.d/vsftpd start
 	exit 0
@@ -88,9 +105,11 @@ while [ ! "`cat /sys/devices/platform/lf1000-nand/cart_hotswap | cut -f1`" -eq "
 	if [ "`expr $TIME_STAMP - $TIME_START`" -ge "2" ] ; then 
 		echo "Failed to set cartridge hotswap to 1.  Unabel to mount cartridge. Starting normally"
 		/usr/bin/app &
-		# Set background color from white to black
-		mlc-control /dev/mlc set background 000000
-		mlc-control /dev/mlc set dirty
+		if [ "$MLC" -eq "1" ] ; then
+			# Set background color from white to black
+			mlc-control /dev/mlc set background 000000
+			mlc-control /dev/mlc set dirty
+		fi
 		exit 1
 	fi
 done
@@ -102,32 +121,69 @@ while [ ! "`cat /proc/mtd | grep -c Cartridge`" -eq "1" ] ; do
 			if [ "`expr $TIME_STAMP - $TIME_START`" -ge "5" ] ; then 
 				echo "No cartridge inserted.  Skipping cartridge mount"
 				/usr/bin/app &
-				# Set background color from white to black
-				mlc-control /dev/mlc set background 000000
-				mlc-control /dev/mlc set dirty
+				if [ "$MLC" -eq "1" ] ; then 
+					# Set background color from white to black
+					mlc-control /dev/mlc set background 000000
+					mlc-control /dev/mlc set dirty
+				fi
 				exit 0
 			fi
 done 
 
 
-if [ ! "`cat /sys/devices/platform/lf1000-nand/cart_ecc_mode`" -eq "1" ] ; then
-	echo 1 > /sys/devices/platform/lf1000-nand/cart_ecc_mode
-	TIME_START=`date +%s`
-	while [ ! "`cat /sys/devices/platform/lf1000-nand/cart_ecc_mode`" -eq "1" ] ; do
-		TIME_STAMP=`date +%s` 
+gpio-control /dev/gpio outenable 2 1  0
+gpio-control /dev/gpio outenable 2 8  0
+gpio-control /dev/gpio outenable 2 9  0
+gpio-control /dev/gpio outenable 2 11 0
+                                                                                
+
+
+#get board id
+BOARD_ID="`cat /sys/devices/platform/lf1000-gpio/board_id`"
+
+echo "Board ID: " $BOARD_ID
+
+if [ $BOARD_ID \< "B" ] ; then   # Emerald HW 
+	CART_ID=$((`gpio-control /dev/gpio invalue 1 5` * 8))
+	CART_ID=$(($CART_ID + (`gpio-control /dev/gpio invalue 1 4` * 4)))
+	CART_ID=$(($CART_ID + (`gpio-control /dev/gpio invalue 1 3` * 2)))
+	CART_ID=$(($CART_ID + (`gpio-control /dev/gpio invalue 1 2`)))
+else
+	CART_ID=$((`gpio-control /dev/gpio invalue 2 9` * 8))
+	CART_ID=$(($CART_ID + (`gpio-control /dev/gpio invalue 2 11` * 4)))
+	CART_ID=$(($CART_ID + (`gpio-control /dev/gpio invalue 2 1` * 2)))
+	CART_ID=$(($CART_ID + (`gpio-control /dev/gpio invalue 2 8`)))
+fi
+                                                                                
+echo "Cart ID: $CART_ID" 
+
+if [ "$CART_ID" = "11" -o "$CART_ID" = "6" -o "$CART_ID" = "15" ] ; then 
+#if [ ! "`dmesg | tail -n 14 | grep 'NAND device' | grep -c 64MiB`" -eq "1" ] ; then 
+	#This means it is a NAND cartridge, so set the ECC mode accordingly
+	if [ "`cat /sys/devices/platform/lf1000-nand/cart_ecc_mode`" -eq "0" ] ; then
+		echo 1 > /sys/devices/platform/lf1000-nand/cart_ecc_mode
+		TIME_START=`date +%s`
+		while [ ! "`cat /sys/devices/platform/lf1000-nand/cart_ecc_mode`" -eq "1" ] ; do
+			TIME_STAMP=`date +%s` 
 	
-		if [ "`expr $TIME_STAMP - $TIME_START`" -ge "2" ] ; then 
-			echo "Failed to set cartridge ecc mode to 1.  Unabel to mount cartridge.  Starting normally"
-			/usr/bin/app &
-			# Set background color from white to black
-			mlc-control /dev/mlc set background 000000
-			mlc-control /dev/mlc set dirty
-			exit 1
-		fi
-	done
+			if [ "`expr $TIME_STAMP - $TIME_START`" -ge "2" ] ; then 
+				echo "Failed to set cartridge ecc mode to 1.  Unabel to mount cartridge.  Starting normally"
+				/usr/bin/app &
+				if [ "$MLC" -eq "1" ] ; then 
+					# Set background color from white to black
+					mlc-control /dev/mlc set background 000000
+					mlc-control /dev/mlc set dirty
+				fi
+				exit 1
+			fi
+		done
+	fi
+else 
+	echo "Skipping enable ECC due to not a NAND cartridge or it is already pre-set"
 fi
 
-/etc/init.d/cartridge start
+
+/etc/init.d/cartridge start -w
 
 TIME_START=`date +%s`
 while [ "`mount | grep -c Cart`" -ne "1" ] ; do
@@ -136,24 +192,41 @@ while [ "`mount | grep -c Cart`" -ne "1" ] ; do
 	if [ "`expr $TIME_STAMP - $TIME_START`" -ge "10" ] ; then 
 		echo "Failed to mount cart"
 		/usr/bin/app &
-		# Set background color from white to black
-		mlc-control /dev/mlc set background 000000
-		mlc-control /dev/mlc set dirty
+		if [ "$MLC" -eq "1" ] ; then 
+			# Set background color from white to black
+			mlc-control /dev/mlc set background 000000
+			mlc-control /dev/mlc set dirty
+		fi	
 		exit 0
 	fi
 done
 
-if [ ! -e /LF/Cart/EmeraldMfgTest/EmeraldMfgTest ] ; then
+if [ -e /LF/Cart/EmeraldMfgTest/EmeraldMfgTest ] ; then
+	echo "Running Emerald Mfg Test from cartridge........."
+	logger -s -t "Emearld App" -p local4.notice "Launched Mfg Test cartridge using trapdoor mode"
+	/LF/Cart/EmeraldMfgTest/LaunchMfgTest.sh &
+	/etc/init.d/telnetd start
+	/etc/init.d/vsftpd start
+	exit 0
+elif [ -e /LF/Cart/MadridMfgTest/MadridMfgTest ] ; then
+	echo "Running Madrid Mfg Test from cartridge........."
+	logger -s -t "Madrid App" -p local4.notice "Launched Mfg Test cartridge using trapdoor mode"
+	/LF/Cart/MadridMfgTest/LaunchMfgTest.sh &
+	/etc/init.d/telnetd start
+	/etc/init.d/vsftpd start
+	exit 0
+else
 	echo "Cartridge is not a Mfg Test cartridge, running in normal mode"
 	/usr/bin/app &
-	# Set background color from white to black
-	mlc-control /dev/mlc set background 000000
-	mlc-control /dev/mlc set dirty
+	if [ "$MLC" -eq "1" ] ; then 
+		# Set background color from white to black
+		mlc-control /dev/mlc set background 000000
+		mlc-control /dev/mlc set dirty
+	fi
 	exit 0
 fi 
-echo "Running Emerald Mfg Test from cartridge........."
-logger -s -t "Emearld App" -p local4.notice "Launched Mfg Test cartridge using trapdoor mode"
-./LF/Cart/EmeraldMfgTest/LaunchMfgTest.sh &
-/etc/init.d/telnetd start
-/etc/init.d/vsftpd start
-exit 0
+
+
+
+
+
diff --git a/LF1000/scripts/functions b/LF1000/scripts/functions
--- a/LF1000/scripts/functions
+++ b/LF1000/scripts/functions
@@ -1,6 +1,11 @@
 # This file implements some common utility functions for the LinuxDist build.
 
 function check_vars() {
+	if [ "X$BUILD_TARGET" == "X" ]; then
+		export BUILD_TARGET="MADRIDANDCIP"
+		echo "BUILD_TARGET not set.  Using default $BUILD_TARGET"
+	fi
+
 	if [ "X$ROOTFS_PATH" == "X" ]; then
 		export ROOTFS_PATH=/home/lfu/nfsroot
 		echo "ROOTFS_PATH not set.  Using default $ROOTFS_PATH"
@@ -57,6 +62,17 @@ function check_vars() {
 		if [ ! -d $LIGHTNING_CORE_PATH ]; then
 			echo "Error: LIGHTNING_CORE_PATH $LIGHTNING_CORE_PATH does not exist."
 			echo "Please set LIGHTNING_CORE_PATH environment variable."
+			exit 1
+		fi
+		
+		if [ "X$LANGUAGEPACK_PATH" == "X" ]; then
+			LANGUAGEPACK_PATH=~/workspace/LanguagePacks/
+			echo "LANGUAGEPACK_PATH not set. Using default $LANGUAGEPACK_PATH"
+		fi
+		
+		if [ ! -d $LANGUAGEPACK_PATH ]; then
+			echo "Error: LANGUAGEPACK_PATH $LANGUAGEPACK_PATH does not exist."
+			echo "Please set LANGUAGEPACK_PATH environment variable."
 			exit 1
 		fi
 	fi
